/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package petri;

import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author Wittmann
 */
public class View extends javax.swing.JFrame {
    
    JLabel [] labels;
    JLabel [] counters;
    
    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        JLabel [] labels={lCPU, lRAM,loutSBridge,linSBridge, loutNBridge,
            linNBridge,lDC,lUSB,lISA,lLPT,lAU,lVP};
        this.labels=labels;
        JLabel [] counters={kCPU, kRAM,koutSBridge,kinSBridge, koutNBridge,
            kinNBridge,kDC,kUSB,kISA,kLPT,kAU,kVP};
        this.counters=counters;
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lCPU = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        loutSBridge = new javax.swing.JLabel();
        linSBridge = new javax.swing.JLabel();
        loutNBridge = new javax.swing.JLabel();
        linNBridge = new javax.swing.JLabel();
        lDC = new javax.swing.JLabel();
        lUSB = new javax.swing.JLabel();
        lISA = new javax.swing.JLabel();
        lLPT = new javax.swing.JLabel();
        lAU = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lVP = new javax.swing.JLabel();
        lRAM = new javax.swing.JLabel();
        koutSBridge = new javax.swing.JLabel();
        kinSBridge = new javax.swing.JLabel();
        koutNBridge = new javax.swing.JLabel();
        kinNBridge = new javax.swing.JLabel();
        kDC = new javax.swing.JLabel();
        kUSB = new javax.swing.JLabel();
        kISA = new javax.swing.JLabel();
        kLPT = new javax.swing.JLabel();
        kAU = new javax.swing.JLabel();
        kVP = new javax.swing.JLabel();
        kRAM = new javax.swing.JLabel();
        kCPU = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        t1Position = new javax.swing.JLabel();
        t2Position = new javax.swing.JLabel();
        t3Position = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        l1.setText("CPU");

        l2.setText("RAM");

        jLabel3.setText("outSBridge");

        jLabel4.setText("inSBridge");

        jLabel5.setText("outNBrigde");

        jLabel6.setText("inNBrigde");

        jLabel7.setText("DC");

        jLabel8.setText("LPT");

        jLabel9.setText("ISA");

        jLabel10.setText("USB");

        jLabel11.setText("AU");

        lCPU.setText("jLabel12");
        lCPU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        loutSBridge.setText("jLabel14");

        linSBridge.setText("jLabel15");

        loutNBridge.setText("jLabel16");

        linNBridge.setText("jLabel17");

        lDC.setText("jLabel18");

        lUSB.setText("jLabel19");

        lISA.setText("jLabel20");

        lLPT.setText("jLabel21");

        lAU.setText("jLabel22");

        jLabel23.setText("VP");

        lVP.setText("jLabel24");

        lRAM.setText("jLabel25");

        koutSBridge.setText("jLabel1");

        kinSBridge.setText("jLabel2");

        koutNBridge.setText("jLabel12");

        kinNBridge.setText("jLabel14");

        kDC.setText("jLabel15");

        kUSB.setText("jLabel16");

        kISA.setText("jLabel17");

        kLPT.setText("jLabel18");

        kAU.setText("jLabel19");

        kVP.setText("jLabel20");

        kRAM.setText("jLabel21");

        kCPU.setText("jLabel22");

        t1.setText("jLabel1");

        t2.setText("jLabel2");

        t3.setText("jLabel12");

        t1Position.setText("jLabel14");

        t2Position.setText("jLabel15");

        t3Position.setText("jLabel16");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lAU))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lLPT))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lISA))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lUSB))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lDC))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(linNBridge))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loutNBridge))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(linSBridge))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loutSBridge))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lRAM))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lCPU))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lVP)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(koutSBridge)
                    .addComponent(kinSBridge)
                    .addComponent(kUSB)
                    .addComponent(kISA)
                    .addComponent(kLPT)
                    .addComponent(kAU)
                    .addComponent(kVP)
                    .addComponent(kRAM)
                    .addComponent(kCPU)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kDC)
                                .addGap(18, 18, 18)
                                .addComponent(t3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kinNBridge)
                                .addGap(18, 18, 18)
                                .addComponent(t2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(koutNBridge)
                                .addGap(18, 18, 18)
                                .addComponent(t1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t1Position)
                            .addComponent(t2Position)
                            .addComponent(t3Position))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1)
                    .addComponent(lCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kCPU))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l2)
                    .addComponent(jLabel13)
                    .addComponent(lRAM)
                    .addComponent(kRAM))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(loutSBridge)
                    .addComponent(koutSBridge))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(linSBridge)
                    .addComponent(kinSBridge))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(loutNBridge)
                    .addComponent(koutNBridge)
                    .addComponent(t1)
                    .addComponent(t1Position))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(linNBridge)
                    .addComponent(kinNBridge)
                    .addComponent(t2)
                    .addComponent(t2Position))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lDC)
                    .addComponent(kDC)
                    .addComponent(t3)
                    .addComponent(t3Position))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lUSB)
                    .addComponent(kUSB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lISA)
                    .addComponent(kISA))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lLPT)
                    .addComponent(kLPT))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lAU)
                    .addComponent(kAU))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lVP)
                    .addComponent(kVP))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        lCPU.getAccessibleContext().setAccessibleName("CPU");
        lCPU.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel kAU;
    public javax.swing.JLabel kCPU;
    public javax.swing.JLabel kDC;
    public javax.swing.JLabel kISA;
    public javax.swing.JLabel kLPT;
    public javax.swing.JLabel kRAM;
    public javax.swing.JLabel kUSB;
    public javax.swing.JLabel kVP;
    public javax.swing.JLabel kinNBridge;
    public javax.swing.JLabel kinSBridge;
    public javax.swing.JLabel koutNBridge;
    public javax.swing.JLabel koutSBridge;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    public javax.swing.JLabel lAU;
    public javax.swing.JLabel lCPU;
    public javax.swing.JLabel lDC;
    public javax.swing.JLabel lISA;
    public javax.swing.JLabel lLPT;
    public javax.swing.JLabel lRAM;
    public javax.swing.JLabel lUSB;
    public javax.swing.JLabel lVP;
    public javax.swing.JLabel linNBridge;
    public javax.swing.JLabel linSBridge;
    public javax.swing.JLabel loutNBridge;
    public javax.swing.JLabel loutSBridge;
    public javax.swing.JLabel t1;
    public javax.swing.JLabel t1Position;
    public javax.swing.JLabel t2;
    public javax.swing.JLabel t2Position;
    public javax.swing.JLabel t3;
    public javax.swing.JLabel t3Position;
    // End of variables declaration//GEN-END:variables
}
